import { SavedPost, Collection } from '@/lib/types';

// 📚 LEARN: Demo data lets users explore the app without importing their own data.
// Each mock post uses picsum.photos with a deterministic seed so images are consistent across reloads.
// We spread saved dates across the last 2 years for realistic relative time display.

function generateId(): string {
  return Math.random().toString(36).substring(2, 13);
}

function randomIgCode(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-';
  let result = '';
  for (let i = 0; i < 11; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// Timestamps spread across the last 2 years
const NOW = Math.floor(Date.now() / 1000);
const DAY = 86400;
const ts = (daysAgo: number) => NOW - (daysAgo * DAY);

export const DEMO_COLLECTIONS: Collection[] = [
  {
    id: 'col-food',
    name: 'Food Inspo',
    emoji: '🍕',
    color: '#F97316',
    createdAt: ts(60),
    sortOrder: 0,
    description: 'Recipes and restaurant finds',
  },
  {
    id: 'col-travel',
    name: 'Travel Goals',
    emoji: '✈️',
    color: '#3B82F6',
    createdAt: ts(55),
    sortOrder: 1,
    description: 'Places to visit',
  },
  {
    id: 'col-design',
    name: 'Design Ref',
    emoji: '🎨',
    color: '#8B5CF6',
    createdAt: ts(45),
    sortOrder: 2,
    description: 'Interior and graphic design inspo',
  },
  {
    id: 'col-fitness',
    name: 'Workout Plans',
    emoji: '💪',
    color: '#22C55E',
    createdAt: ts(40),
    sortOrder: 3,
    description: 'Exercise routines and motivation',
  },
];

export const DEMO_POSTS: SavedPost[] = [
  // ── Food / Recipe (8 posts) ──────────────────────────────────
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food1/400/400',
    caption: 'Homemade sourdough pizza with burrata and fresh basil 🍕',
    tags: ['food', 'recipe', 'pizza', 'homemade'],
    collectionId: 'col-food',
    savedAt: ts(730),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food2/400/500',
    caption: 'The perfect matcha latte art — oat milk, ceremonial grade 🍵',
    tags: ['food', 'matcha', 'coffee-shop', 'aesthetic'],
    collectionId: 'col-food',
    savedAt: ts(680),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food3/400/400',
    caption: 'Japanese ramen from scratch — 48 hour bone broth 🍜',
    tags: ['food', 'ramen', 'japanese', 'recipe'],
    collectionId: 'col-food',
    savedAt: ts(520),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food4/400/500',
    caption: 'Weekend farmers market haul — seasonal produce is unmatched',
    tags: ['food', 'farmers-market', 'healthy', 'seasonal'],
    collectionId: 'col-food',
    savedAt: ts(400),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food5/400/400',
    caption: 'Pasta aglio e olio — 5 ingredients, maximum flavor 🍝',
    tags: ['food', 'pasta', 'italian', 'minimalist'],
    collectionId: 'col-food',
    savedAt: ts(350),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food6/400/500',
    caption: 'Thai green curry with homemade paste 🌶️',
    tags: ['food', 'thai', 'curry', 'spicy'],
    collectionId: 'col-food',
    savedAt: ts(250),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food7/400/400',
    caption: 'Avocado toast but make it gourmet — poached egg, chili flakes, microgreens',
    tags: ['food', 'brunch', 'avocado', 'healthy'],
    collectionId: 'col-food',
    savedAt: ts(180),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/food8/400/500',
    caption: 'Chocolate lava cake that actually works every time 🍫',
    tags: ['food', 'dessert', 'chocolate', 'baking'],
    collectionId: null,
    savedAt: ts(90),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },

  // ── Travel / Architecture (6 posts) ──────────────────────────
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/travel1/400/500',
    caption: 'Santorini at golden hour — the light here is unreal 🇬🇷',
    tags: ['travel', 'greece', 'golden-hour', 'architecture'],
    collectionId: 'col-travel',
    savedAt: ts(700),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/travel2/400/400',
    caption: 'Tokyo side streets at 2am — vending machine glow 🇯🇵',
    tags: ['travel', 'japan', 'night', 'neon', 'street'],
    collectionId: 'col-travel',
    savedAt: ts(600),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/travel3/400/500',
    caption: 'Hiking the Dolomites — every angle is a postcard 🏔️',
    tags: ['travel', 'italy', 'hiking', 'mountains', 'nature'],
    collectionId: 'col-travel',
    savedAt: ts(480),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/travel4/400/400',
    caption: 'Marrakech riads are another level of design 🇲🇦',
    tags: ['travel', 'morocco', 'architecture', 'colorful'],
    collectionId: 'col-travel',
    savedAt: ts(320),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/travel5/400/500',
    caption: 'NYC from the Brooklyn Bridge at sunrise 🌅',
    tags: ['travel', 'nyc', 'sunrise', 'urban'],
    collectionId: null,
    savedAt: ts(200),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/travel6/400/400',
    caption: 'Portuguese azulejos are endlessly beautiful 🇵🇹',
    tags: ['travel', 'portugal', 'tiles', 'architecture'],
    collectionId: 'col-travel',
    savedAt: ts(120),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },

  // ── Interior Design / Aesthetics (5 posts) ───────────────────
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/design1/400/500',
    caption: 'Japandi living room — when minimalism meets warmth',
    tags: ['interior-design', 'japandi', 'minimalist', 'living-room'],
    collectionId: 'col-design',
    savedAt: ts(650),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/design2/400/400',
    caption: 'Dark academia study corner — walnut desk, brass lamp, leather',
    tags: ['interior-design', 'dark-academia', 'study', 'moody'],
    collectionId: 'col-design',
    savedAt: ts(550),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/design3/400/500',
    caption: 'Concrete and terrazzo bathroom — brutalist but cozy',
    tags: ['interior-design', 'bathroom', 'brutalist', 'concrete'],
    collectionId: 'col-design',
    savedAt: ts(420),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/design4/400/400',
    caption: 'Kitchen shelf styling — the art of looking effortless 🫖',
    tags: ['interior-design', 'kitchen', 'styling', 'shelfie'],
    collectionId: 'col-design',
    savedAt: ts(280),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/design5/400/500',
    caption: 'Arch doorways and plaster walls — Mediterranean dream home',
    tags: ['interior-design', 'mediterranean', 'arches', 'warm'],
    collectionId: null,
    savedAt: ts(150),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },

  // ── Fashion / Outfit (4 posts) ────────────────────────────────
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fashion1/400/500',
    caption: 'Capsule wardrobe essentials — 15 pieces, infinite outfits',
    tags: ['fashion', 'capsule-wardrobe', 'minimalist', 'outfit-inspo'],
    collectionId: null,
    savedAt: ts(620),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fashion2/400/400',
    caption: 'Layering for fall — oversized coat, turtleneck, wide leg 🍂',
    tags: ['fashion', 'fall', 'layering', 'streetstyle'],
    collectionId: null,
    savedAt: ts(450),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fashion3/400/500',
    caption: 'Sneaker rotation 2024 — New Balance 990v5 still on top',
    tags: ['fashion', 'sneakers', 'new-balance', 'streetwear'],
    collectionId: null,
    savedAt: ts(300),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fashion4/400/400',
    caption: 'Linen everything for summer — effortless Mediterranean vibes',
    tags: ['fashion', 'linen', 'summer', 'mediterranean'],
    collectionId: null,
    savedAt: ts(160),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },

  // ── Fitness / Wellness (4 posts) ──────────────────────────────
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fitness1/400/400',
    caption: 'Push pull legs split — the only program you need 💪',
    tags: ['fitness', 'workout', 'gym', 'strength'],
    collectionId: 'col-fitness',
    savedAt: ts(580),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fitness2/400/500',
    caption: 'Morning yoga flow — 15 min routine for flexibility',
    tags: ['fitness', 'yoga', 'morning-routine', 'flexibility'],
    collectionId: 'col-fitness',
    savedAt: ts(440),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fitness3/400/400',
    caption: 'High protein meal prep — 5 days in 2 hours',
    tags: ['fitness', 'meal-prep', 'protein', 'healthy'],
    collectionId: 'col-fitness',
    savedAt: ts(260),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/fitness4/400/500',
    caption: 'Running form tips that changed everything for me 🏃',
    tags: ['fitness', 'running', 'form', 'tips'],
    collectionId: null,
    savedAt: ts(100),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },

  // ── Quotes / Typography (3 posts) ─────────────────────────────
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/quote1/400/400',
    caption: '"The only way to do great work is to love what you do." — Steve Jobs',
    tags: ['quote', 'motivation', 'typography', 'minimalist'],
    collectionId: null,
    savedAt: ts(500),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/quote2/400/500',
    caption: '"Design is not just what it looks like. Design is how it works." — Steve Jobs',
    tags: ['quote', 'design', 'typography', 'inspiration'],
    collectionId: null,
    savedAt: ts(380),
    addedToArchivr: ts(1),
    aiAnalyzed: true,
  },
  {
    id: generateId(),
    url: `https://www.instagram.com/p/${randomIgCode()}/`,
    thumbnailUrl: 'https://picsum.photos/seed/quote3/400/400',
    caption: '"Simplicity is the ultimate sophistication." — Leonardo da Vinci',
    tags: ['quote', 'simplicity', 'typography', 'classic'],
    collectionId: null,
    savedAt: ts(50),
    addedToArchivr: ts(1),
    aiAnalyzed: false,
  },
];
